config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'about', to: 'pages#about'
  resources :cars
  get 'signup', to: 'users#new'
  
  resources :users, except: [:new]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum:1, maximum:100}
  validates :description, presence: true, length: {minimum:3, maximum:1000}
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email= email.downcase}
  before_save {self.username= username.downcase}
  has_many :cars
  validates :username, presence: true, 
    uniqueness: { case_sensitive: false }, length: {minimum:3, maximum:25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
  validates :email, presence: true, 
    length: { maximum:25 }, uniqueness: { case_sensitive: false },
    format: {with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :params_id, only: [:show, :edit, :update, :destroy]

  def show
    # Check private
  end

  def index
    @car= Car.all
  end

  def new
    @car= Car.new
  end
  
  def create
    @car= Car.new(permit_id)
    @car.user= User.first
    if @car.save
    redirect_to @car
    else
    render 'new'
    end
  end

  def edit
    # Check private
  end

  def update
    # check private
    if @car.update(permit_id)
      flash[:notice] = "Car was updated"
      redirect_to @car
    else
      render 'edit'
    end  
  end

  def destroy
    # Check private
    @car.destroy
    redirect_to cars_path
  end

  private

  def params_id
    @car= Car.find(params[:id])
  end
  
  def permit_id
    params.require(:car).permit(:title, :description)
  end
  
  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user= User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to Fiscal Park #{@user.username}, you have successfully signed up"
      redirect_to cars_path
    else
      render 'new'
    end
  end

  def edit
    @user= User.find(params[:id])
  end
  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]= "Your User was updated"
      redirect_to cars_path
    else 
      render 'edit'
    end
  end

  def show
    @user= User.find(params[:id])
    @car= @user.cars
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  end

app/helpers/application_helper.rb
module ApplicationHelper

def gravatar_for(user, options= {size:80})
  email_address= user.email.downcase
  hash = Digest::MD5.hexdigest(email_address)
  size= options[:size]
  gravatar_url= "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
  image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cars/_cars.html.erb
<h1 class= "text-center mt-4 text-white" >Cars Index</h1>
<div class="form-group row justify-content-center">
  <%= link_to 'Create new', new_car_path, class: "btn btn-outline-warning mt-4"%>
  </div>
<% @car.each do |f| %>
<div class="container">
    <div class="row justify-content-md-center mt-4">
      <div class="col-8 mt-4">
        <div class="card text-center">
          <div class="card-header">
           <small>Created by: <%= f.user.username %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= f.title  %></h5>
            <p class="card-text"><%= f.description %></p>
            <%= link_to "Edit", edit_car_path(f), class: "btn btn-outline-warning"%>
            <%= link_to "View", car_path(f), class: "btn btn-outline-info"%>
            <%= link_to "Destroy", car_path(f), method: :delete, class: "btn btn-outline-danger"%>
          </div>
          <div class="card-footer text-muted">
            <%= f.created_at %>
          </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/cars/_form.html.erb
<div class="container">
<%= render 'shared/errors', obj: @car %>
  <div class="row justify-content-center">
  <div class="col-10">
  <%= form_with(model: @car, class: "shadow p-3 mb-5 bg-white rounded", local: true) do |f| %>
  <div class="form-group row">
    <div class="col-sm-10 ml-4" ">

    <%= f.label :title, "Title: "%>
    <%= f.text_field :title, class: "form-control shadow rounder"  %>

  </div>
    </div>
  <div class="form-group row">
    <div class="col-sm-10 ml-4">
    <%= f.label :description, "Description: " %><br/>
    <%= f.text_area :description, rows: 10, class: "form-control shadow rounder"  %> 
  </div>
    </div>
    <div class="form-group row justify-content-center">
  <%=f.submit class: "btn btn-outline-warning "%>
  
    </div>
    </div>
        
    <% end %>

  </div>
  
</div>

app/views/cars/edit.html.erb
<h1 class="display-3 text-center">Cars</h1>
<br/>
<br/>

<%= render 'form' %>
 <div class="form-group row justify-content-center">
<p>
<%= link_to 'All Cars', cars_path, class: "btn btn-outline-info text-white" %>
</p>
</div>

app/views/cars/index.html.erb
<%= render 'pages/navigation' %>

<%= render 'cars' %>

<%= link_to 'Create new', new_car_path %>

app/views/cars/new.html.erb
<%= render 'pages/navigation' %>
<h1 class="display-3 text-center text-white">Create new Car</h1>
<br/>
<br/>

<%= render 'form' %>

<div class="form-group row justify-content-center">
  <%= link_to 'Cancel and return', cars_path, class: "btn btn-outline-warning mt-4"%>
</div>

app/views/cars/show.html.erb
<%= render 'pages/navigation' %>

<h1 class= "display-4 text-center text-white">Cars and Models</h1>

<br/>
<br/>
<div class="form-group col justify-content-center ml-5">
  <div class="col-sm-10 ml-4 shadow p-3 mb-5 bg-white rounded ">
    <div class="form-control-plaintext shadow-none p-3 mb-5 bg-light rounded">
      <p><strong>Title: </strong> <%= @car.title %> </p>
    </div>
    <div class="form-control-plaintext shadow-none p-3 mb-5 bg-light rounded">
      <p><strong>Description: </strong> <%= @car.description %> </p>
    </div>
    <div class="form-group row justify-content-center">
    <p><%= link_to 'Edit', edit_car_path, class: "btn btn-outline-warning mr-3"%></p><br/>
    <p><%= link_to 'Create new', new_car_path, class: "btn btn-outline-warning"%></p>
    </div>
    </div>
  <div class="form-group row justify-content-center">
      <%= link_to 'All Cars', cars_path, class: "btn btn-outline-info text-white" %>
  </div>
</div>

app/views/layouts/_messages.html.erb
    <% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible fade show">
      <%= msg %>
    </div>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_navigation.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-light">
      <%= link_to 'TESLA', root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon" style="color:#fff"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Cars', cars_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Cars
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Make a new car', new_car_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to 'See all cars', cars_path, class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
      <div class="fixed-bottom"><footer class="container-fluid w-100 bg-dark text-light py-3"><p class= "text-center">Copyright (c) 2011-2021 FiscalPark, Inc.</p></div>

    </nav>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/pages/index.html.erb
<%= render 'navigation' %>

<div class="container col-10" id="home-container">
  <div class="jumbotron text-center text-white">
    <h1 class="display-4">Stripe Payments</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to 'Sign Up!', signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

<div class="container col-1">
<%= link_to 'Cars', cars_path, class: "btn btn-outline-warning"  %>
</div>

app/views/shared/_errors.html.erb
<% if   obj.errors.any? %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>The following errors prevented the article from being saved</strong>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
    <% end %>
  

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', cars_path, class: "text-info" %>
    </div>
  </div>
</div> 

app/views/users/edit.html.erb
<h1 class="display-3 text-center text-white">Cars</h1>
<br/>
<br/>

<%= render 'form' %>

<div class="form-group row justify-content-center">
  <p>
  <%= link_to 'All Cars', cars_path, class: "btn btn-outline-info text-white" %>
  </p>
</div>

app/views/users/new.html.erb
<%= render 'pages/navigation' %>
<h1 class="display-3 text-center text-white">Create new User</h1>
<br/>
<br/>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'pages/navigation' %>

<h1 class= "display-4 text-center text-white">Cars and Models</h1>
<%= gravatar_for @user, size: 200 %>
<br/>
<br/>

<%= render 'cars/cars' %>